name: NPM Package Publishing

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
      npm_access:
        required: false
        type: string
        default: 'restricted'
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Set package access
        run: |
          if [ -f "package.json" ]; then
            npm pkg set publishConfig.access=${{ inputs.npm_access }}
          fi

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}