name: Semantic Release NPM Publishing

on:
  workflow_call:
    inputs:
      config_path:
        description: 'Pfad zur npm-release Config'
        required: false
        type: string
        default: './configs/npm-release.config.js'
    secrets:
      NPM_TOKEN:
        description: 'NPM Authentifizierungstoken'
        required: true

jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout Template Repository
        uses: actions/checkout@v3
        with:
          repository: linuspalma/cicd-pipelines
          ref: main
          path: template

      - name: List Template Repository
        run: ls -R template

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Template Dependencies
        working-directory: template
        run: npm ci

      - name: Semantic Release NPM Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_PATH: $(pwd)/template/node_modules
        run: npx semantic-release --extends=$(pwd)/template/configs/npm-release.config.js