name: NPM Package Publishing

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: 'lts/*'
      npm_access:
        required: false
        type: string
        default: 'restricted'
    secrets:
      NPM_TOKEN:
        description: 'NPM Authentifizierungstoken'
        required: true

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          #persist-credentials: false

      - name: Ensure latest changes are fetched
        run: |
          git fetch --prune
          git checkout main
          git pull

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Project Dependencies
        run: npm ci

      - name: Set package access
        run: |
          if [ -f "package.json" ]; then
            npm pkg set publishConfig.access=${{ inputs.npm_access }}
          fi

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}