name: Semantic Release Template

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
    secrets:
      GH_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create release config
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              ["@semantic-release/git", {
                "assets": ["package.json", "CHANGELOG.md"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }]
            ]
          }
          EOF

      - run: npm ci

      - name: Semantic Release with Version Update
        run: |
          # Führe semantic-release aus und speichere die Version
          VERSION=$(npx semantic-release --dry-run | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+' || true)
          
          if [ ! -z "$VERSION" ]; then
            # Aktualisiere package.json
            sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
          
            # Führe semantic-release richtig aus
            npx semantic-release
          else
            echo "No new version to be released"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}