name: Semantic Release Template

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
    secrets:
      GH_TOKEN:
        required: true
      # NPM_TOKEN:
      #   required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_RELEASE_CONFIG: |
            {
              "plugins": [
                "@semantic-release/commit-analyzer",
                "@semantic-release/release-notes-generator",
                "@semantic-release/changelog",
                ["@semantic-release/git", {
                  "assets": ["package.json", "CHANGELOG.md"],
                  "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
                }]
              ]
            }

