name: Semantic Release Template

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
    secrets:
      GH_TOKEN:
        required: true
      # NPM_TOKEN:
      #   required: true

jobs:
  semantic-release:
    uses: linuspalma/cicd-pipelines/.github/workflows/semantic-release.yml@main
    with:
      node_version: '20'
      config: |
        {
          "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/changelog",
            ["@semantic-release/git", {
              "assets": ["package.json", "CHANGELOG.md"],
              "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
            }]
          ]
        }
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

