name: Semantic Release Template

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
    secrets:
      GH_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Get Next Version
        id: next-version
        run: |
          npx semantic-release --dry-run --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}