name: Semantic Release Template

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '18'
    secrets:
      GH_TOKEN:
        required: true
      # NPM_TOKEN:
      #   required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Wichtig: Volle Git-History
          persist-credentials: false  # Wichtig für den Git-Push

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create release config
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              ["@semantic-release/npm", {
                "npmPublish": false
              }],
              ["@semantic-release/git", {
                "assets": ["package.json", "CHANGELOG.md"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }]
            ]
          }
          EOF

      - run: npm ci

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

          

