name: Semantic Release versioning

on:
  workflow_call:
    inputs:
      config_path:
        required: false
        type: string
        default: './configs/versioning.config.js'
    secrets:
      GH_TOKEN:
        required: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout Template Repository
        uses: actions/checkout@v3
        with:
          repository: linuspalma/cicd-pipelines
          ref: main
          path: template
      - name: List Template Repository
        run: ls -R template

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --extends=template/configs/versioning.config.js