name: Semantic Release versioning

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  versioning:
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Create temp config
        run: |
          echo '{
            "branches": ["main"],
            "plugins": [
                  '@semantic-release/commit-analyzer',
                  '@semantic-release/release-notes-generator',
                  '@semantic-release/changelog',
                  ['@semantic-release/npm', {
                    "npmPublish": false
                  }],
                  ['@semantic-release/git', {
                    "assets": [
                      "package.json",
                      "CHANGELOG.md"
                    ],
                    "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
                  }],
                  '@semantic-release/github'
            ]
          }' > .releaserc.json


      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --extends=${{ inputs.config_path }}